baseURL = 'https://indigosec.dev/'
languageCode = 'en-us'
title = 'indigo <3'
theme = "m10c"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2